flags: {}
packages:
- '.'
compiler-check: newer-minor
resolver: lts-8.3
extra-deps:
  - distributed-process-0.6.6
  - distributed-process-async-0.2.3
  - distributed-process-extras-0.2.1.2
  - distributed-process-client-server-0.1.3.2
  - LogicGrowsOnTrees-1.1.0.2
